//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NStore.Models.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChiTietPhieuXuat
    {
        public int id { get; set; }
        public Nullable<int> idPhieuXuat { get; set; }
        public Nullable<int> idSanPham { get; set; }
        public Nullable<int> soLuongXuat { get; set; }
    
        public virtual PhieuXuat PhieuXuat { get; set; }
        public virtual SanPham SanPham { get; set; }
    }
}
