//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NStore.Models.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class DonHang
    {
        public DonHang()
        {
            this.ChiTietDonHang = new HashSet<ChiTietDonHang>();
            this.PhieuXuat = new HashSet<PhieuXuat>();
        }
    
        public int id { get; set; }
        public Nullable<int> idKhachHang { get; set; }
        public Nullable<System.DateTime> ngayDatHang { get; set; }
        public string diaChiGiaoHang { get; set; }
        public Nullable<System.DateTime> ngayGiaoHang { get; set; }
        public string ghiChu { get; set; }
        public string hinhThucThanhToan { get; set; }
        public Nullable<int> thanhTien { get; set; }
        public Nullable<bool> trangThaiThanhToan { get; set; }
        public Nullable<byte> trangThaiDonHang { get; set; }
    
        public virtual ICollection<ChiTietDonHang> ChiTietDonHang { get; set; }
        public virtual KhachHang KhachHang { get; set; }
        public virtual ICollection<PhieuXuat> PhieuXuat { get; set; }
    }
}
