//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NStore.Models.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class NhaCungCap
    {
        public NhaCungCap()
        {
            this.PhieuNhap = new HashSet<PhieuNhap>();
        }
    
        public int id { get; set; }
        public string tenNhaCungCap { get; set; }
        public string email { get; set; }
        public string soDienThoai { get; set; }
        public string diaChi { get; set; }
    
        public virtual ICollection<PhieuNhap> PhieuNhap { get; set; }
    }
}
