//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NStore.Models.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class NhanVienTiepNhanDonHang
    {
        public int id { get; set; }
        public Nullable<int> idDonHang { get; set; }
        public Nullable<int> idNhanVien { get; set; }
        public Nullable<System.DateTime> ngayNhanDon { get; set; }
        public Nullable<byte> trangThaiDonHang_Cu { get; set; }
        public Nullable<byte> trangThaiDonHang_Moi { get; set; }
    
        public virtual DonHang DonHang { get; set; }
        public virtual NhanVien NhanVien { get; set; }
    }
}
