//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NStore.Models.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class NhanVien
    {
        public NhanVien()
        {
            this.PhieuNhap = new HashSet<PhieuNhap>();
            this.PhieuXuat = new HashSet<PhieuXuat>();
        }
    
        public int id { get; set; }
        public string taiKhoan { get; set; }
        public string matKhau { get; set; }
        public string hoTen { get; set; }
        public string CCCD { get; set; }
        public string email { get; set; }
        public string soDienThoai { get; set; }
        public Nullable<System.DateTime> ngaySinh { get; set; }
        public string gioiTinh { get; set; }
        public string diaChi { get; set; }
        public Nullable<byte> chucVu { get; set; }
    
        public virtual ICollection<PhieuNhap> PhieuNhap { get; set; }
        public virtual ICollection<PhieuXuat> PhieuXuat { get; set; }
    }
}
