//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NStore.Models.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class NhomDanhMuc
    {
        public NhomDanhMuc()
        {
            this.DanhMuc = new HashSet<DanhMuc>();
        }
    
        public int id { get; set; }
        public string tenNhomDanhMuc { get; set; }
        public string img { get; set; }
    
        public virtual ICollection<DanhMuc> DanhMuc { get; set; }
    }
}
