//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NStore.Models.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhieuXuat
    {
        public PhieuXuat()
        {
            this.ChiTietPhieuXuat = new HashSet<ChiTietPhieuXuat>();
        }
    
        public int id { get; set; }
        public Nullable<int> idNhanVien { get; set; }
        public Nullable<System.DateTime> ngayXuat { get; set; }
        public Nullable<int> idDonHang { get; set; }
    
        public virtual ICollection<ChiTietPhieuXuat> ChiTietPhieuXuat { get; set; }
        public virtual NhanVien NhanVien { get; set; }
        public virtual DonHang DonHang { get; set; }
    }
}
