//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NStore.Models.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class SanPham
    {
        public SanPham()
        {
            this.ChiTietDonHang = new HashSet<ChiTietDonHang>();
            this.ChiTietPhieuNhap = new HashSet<ChiTietPhieuNhap>();
            this.ChiTietPhieuXuat = new HashSet<ChiTietPhieuXuat>();
            this.GioHang = new HashSet<GioHang>();
            this.SanPhamImage = new HashSet<SanPhamImage>();
            this.SanPhamYeuThich = new HashSet<SanPhamYeuThich>();
        }
    
        public int id { get; set; }
        public string tenSanPham { get; set; }
        public Nullable<int> idDanhMuc { get; set; }
        public string img { get; set; }
        public string mota { get; set; }
        public string kichThuoc { get; set; }
        public string mauSac { get; set; }
        public string chatLieu { get; set; }
        public string xuatXu { get; set; }
        public Nullable<int> donGia { get; set; }
        public Nullable<byte> giamGia { get; set; }
        public Nullable<int> soLuongTon { get; set; }
    
        public virtual ICollection<ChiTietDonHang> ChiTietDonHang { get; set; }
        public virtual ICollection<ChiTietPhieuNhap> ChiTietPhieuNhap { get; set; }
        public virtual ICollection<ChiTietPhieuXuat> ChiTietPhieuXuat { get; set; }
        public virtual DanhMuc DanhMuc { get; set; }
        public virtual ICollection<GioHang> GioHang { get; set; }
        public virtual ICollection<SanPhamImage> SanPhamImage { get; set; }
        public virtual ICollection<SanPhamYeuThich> SanPhamYeuThich { get; set; }
    }
}
